### ISSUE TITLE
Enhancements & Cleanup - Project Request Form/Dashboard.html

### ISSUE THREAD

**Issue by dynamiccookies** [CarverCounty/Scripts_Public#1]
[Project Request Form](../tree/master/Project_Request_Form)/[Dashboard](../blob/master/Project_Request_Form/Dashboard.html)

**Task List:**
- [x] Hide Departments dropdown when only one returned or remove [comment](../blob/af4c788e4cd2862ef54b10a3915630a2fefd4644/Project%20Request%20Form/Dashboard.html#L35)
- [x] Add comments to code
- [x] Remove need for jQuery on line [#78](../blob/af4c788e4cd2862ef54b10a3915630a2fefd4644/Project%20Request%20Form/Dashboard.html#L78)
  - [x] Remove jQuery inclusion on lines [#19-22](../blob/af4c788e4cd2862ef54b10a3915630a2fefd4644/Project%20Request%20Form/Dashboard.html#L19-L22)
- [x] Clean up [loadPage() function](../blob/af4c788e4cd2862ef54b10a3915630a2fefd4644/Project%20Request%20Form/Dashboard.html#L26-L29) - Call functions directly in [`<body onLoad=''>`](../blob/af4c788e4cd2862ef54b10a3915630a2fefd4644/Project%20Request%20Form/Dashboard.html#L10)
- [x] Combine [CSS](../blob/af4c788e4cd2862ef54b10a3915630a2fefd4644/Project%20Request%20Form/Dashboard.html#L4-L8) where possible
- [x] Add 'Loading...' gif pinwheel for long query runs???
- [x] Confirm [line #49](../blob/f3a21b50045bfd41e8f530aaafbcae17cf5336c0/Project%20Request%20Form/Dashboard.html#L49) isn't needed - `<OrderBy>` is carryover from other queries
